/**
 * Default Presets for Photo Prompt Generator
 * These presets provide quick starting points for common photography scenarios
 */

const DEFAULT_PRESETS = {
    "phone_popout_fashion": {
        name: "Phone Pop-out OOTD", icon: "📱", category: "trending",
        description: "Hyper-realistic optical illusion - model stepping out of smartphone screen with fashion breakdown",
        credit: "https://x.com/underwoodxie96",
        data: {
            subject_type: "fashion",
            style: "photorealistic",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "caucasian",
                age_group: "young adult",
                body_type: "petite",
                hair_style: "long flowing",
                hair_color: "dark brown",
                expression: "playful",
                pose: "action pose",
                clothing_style: "elegant",
                clothing_type: "sweater",
                clothing_color: "brown",
                makeup_style: "natural minimal",
                skin_type: "fair"
            }],
            eye_look: "alluring",
            eye_energy: "confident",
            eye_direction: "looking at viewer",
            mouth_position: "blowing a kiss",
            mouth_energy: "chic",
            face_features: "high nose bridge",
            hair_effect: "wind-blown",
            body_frame: "petite",
            body_definition: "defined waist",
            skin_visible_areas: "face and hands",
            skin_tone: "fair caucasian",
            skin_texture: "ultra-realistic",
            skin_lighting_effect: "soft daylight",
            pose_position: "emerging",
            pose_base: "dynamic",
            pose_energy: "energetic",
            clothing_effect: "high-quality textile",
            clothing_details: "texture emphasis",
            device_type: "smartphone",
            device_details: "camera UI visible",
            prop_type: "text overlay",
            illusion_type: "pop-out effect",
            illusion_device: "smartphone screen",
            camera_style: "DSLR photography",
            shot_type: "composite photography",
            photo_texture: "sharp pixels",
            depth_of_field: "bokeh background",
            background_elements: "park bench",
            background_atmosphere: "cinematic",
            vibe_energy: "sophisticated",
            vibe_aesthetic: "OOTD breakdown",
            vibe_authenticity: "photorealistic",
            vibe_intimacy: "POV",
            lighting: "natural light",
            mood: "energetic",
            color_palette: "warm tones",
            setting: "european plaza",
            season: "autumn",
            camera_angle: "high angle",
            quality_modifiers: "ultra detailed",
            _sceneObjects: [
                { label: "Smartphone with burgundy case", category: "props", location: "foreground", prominence: "primary", color: "burgundy", material: "phone case", state: "active screen showing iOS Camera UI" },
                { label: "Photographer's hand with gold rings", category: "props", location: "foreground", prominence: "primary", color: "skin tone with gold jewelry" },
                { label: "Green park bench", category: "furniture", location: "background", prominence: "secondary", color: "green" },
                { label: "Autumn leaves", category: "natural", location: "background", prominence: "background", color: "orange and brown" }
            ],
            _semanticRelationships: [
                { subject: "Woman", action: "emerging from", object: "smartphone screen" },
                { subject: "Phone screen", action: "displaying", object: "legs with boots inside camera UI" },
                { subject: "Hand", action: "holding", object: "smartphone" }
            ],
            additional_details: "Hyper-realistic optical illusion photograph. Young Caucasian woman stepping out of smartphone screen held in hand. iOS Camera UI visible on screen. POV shot looking down at hand. Macro lens for phone details."
        }
    },

    "neon_cyberpunk_portrait": {
        name: "Neon Cyberpunk Portrait", icon: "🌃", category: "trending",
        description: "Futuristic cyberpunk portrait with neon lighting and urban atmosphere",
        credit: "https://x.com/midaborney",
        data: {
            subject_type: "portrait",
            style: "cinematic",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "east asian",
                age_group: "young adult",
                body_type: "slim",
                hair_style: "asymmetric bob",
                hair_color: "neon pink highlights",
                expression: "intense",
                pose: "three quarter view",
                clothing_style: "cyberpunk",
                clothing_type: "leather jacket",
                clothing_color: "black with neon accents",
                makeup_style: "bold lip",
                skin_type: "fair"
            }],
            eye_look: "piercing",
            eye_energy: "intense",
            eye_direction: "looking at viewer",
            mouth_position: "slightly parted",
            mouth_energy: "mysterious",
            face_features: "sharp cheekbones",
            hair_effect: "neon glow reflection",
            body_frame: "slim",
            body_definition: "defined shoulders",
            skin_visible_areas: "face and neck",
            skin_tone: "pale with neon reflections",
            skin_texture: "smooth porcelain",
            skin_lighting_effect: "neon color cast",
            pose_position: "standing",
            pose_base: "confident stance",
            pose_energy: "powerful",
            clothing_effect: "reflective surfaces",
            clothing_details: "LED strips embedded",
            device_type: "holographic display",
            device_details: "floating UI elements",
            prop_type: "cybernetic implants",
            illusion_type: "holographic overlay",
            illusion_device: "augmented reality",
            camera_style: "mirrorless",
            shot_type: "portrait photography",
            photo_texture: "film grain",
            depth_of_field: "shallow focus",
            background_elements: "neon signs",
            background_atmosphere: "dystopian urban",
            vibe_energy: "edgy",
            vibe_aesthetic: "neo-noir",
            vibe_authenticity: "stylized realism",
            vibe_intimacy: "confrontational",
            lighting: "neon lighting",
            mood: "mysterious",
            color_palette: "neon colors",
            setting: "tokyo alley",
            season: "night",
            camera_angle: "low angle",
            quality_modifiers: "8k resolution",
            _sceneObjects: [
                { label: "Neon sign Japanese text", category: "props", location: "background", prominence: "secondary", color: "pink and blue neon", state: "glowing" },
                { label: "Rain puddles", category: "natural", location: "ground", prominence: "secondary", color: "reflective", state: "reflecting neon lights" },
                { label: "Steam vents", category: "atmosphere", location: "background", prominence: "background", state: "rising steam" }
            ],
            _semanticRelationships: [
                { subject: "Model", action: "standing in", object: "neon-lit alley" },
                { subject: "Neon lights", action: "reflecting off", object: "wet surfaces" },
                { subject: "Steam", action: "rising around", object: "model" }
            ],
            additional_details: "Cyberpunk portrait with strong neon pink and blue lighting. Rain-soaked Tokyo backstreet atmosphere. Blade Runner inspired aesthetic. Reflections in puddles and on leather jacket. Atmospheric haze from steam vents."
        }
    },

    "golden_hour_beach": {
        name: "Golden Hour Beach", icon: "🌅", category: "portrait",
        description: "Dreamy beach portrait during golden hour with warm natural lighting",
        credit: "https://x.com/portraitmaster",
        data: {
            subject_type: "portrait",
            style: "photorealistic",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "latin american",
                age_group: "young adult",
                body_type: "athletic",
                hair_style: "beachy waves",
                hair_color: "sun-kissed brown",
                expression: "serene",
                pose: "natural candid",
                clothing_style: "bohemian",
                clothing_type: "flowing dress",
                clothing_color: "white",
                makeup_style: "no makeup",
                skin_type: "sun-kissed"
            }],
            eye_look: "dreamy",
            eye_energy: "soft",
            eye_direction: "looking away",
            mouth_position: "gentle smile",
            mouth_energy: "peaceful",
            face_features: "natural freckles",
            hair_effect: "backlit glow",
            body_frame: "athletic",
            body_definition: "toned arms",
            skin_visible_areas: "face arms shoulders",
            skin_tone: "warm golden",
            skin_texture: "natural with sun spots",
            skin_lighting_effect: "golden rim light",
            pose_position: "walking",
            pose_base: "relaxed",
            pose_energy: "carefree",
            clothing_effect: "translucent backlit",
            clothing_details: "flowing in wind",
            device_type: "none",
            device_details: "none",
            prop_type: "straw hat",
            illusion_type: "none",
            illusion_device: "none",
            camera_style: "DSLR photography",
            shot_type: "lifestyle photography",
            photo_texture: "soft focus",
            depth_of_field: "creamy bokeh",
            background_elements: "ocean waves",
            background_atmosphere: "magical golden",
            vibe_energy: "free-spirited",
            vibe_aesthetic: "boho chic",
            vibe_authenticity: "candid natural",
            vibe_intimacy: "personal moment",
            lighting: "golden hour",
            mood: "peaceful",
            color_palette: "warm tones",
            setting: "tropical beach",
            season: "summer",
            camera_angle: "eye level",
            quality_modifiers: "professional quality",
            _sceneObjects: [
                { label: "Ocean waves", category: "natural", location: "background", prominence: "secondary", color: "turquoise", state: "gently rolling" },
                { label: "White sand", category: "natural", location: "ground", prominence: "background", color: "golden white" },
                { label: "Straw hat", category: "props", location: "hand", prominence: "secondary", color: "natural straw" }
            ],
            _semanticRelationships: [
                { subject: "Model", action: "walking along", object: "shoreline" },
                { subject: "Dress", action: "flowing in", object: "ocean breeze" },
                { subject: "Sun", action: "backlighting", object: "model's hair" }
            ],
            additional_details: "Golden hour beach portrait. Sun low on horizon creating warm backlight. White dress translucent against sunlight. Hair glowing with rim light. Barefoot on sand. Carefree summer vibes. Shot during magic hour."
        }
    },

    "vintage_film_noir": {
        name: "Vintage Film Noir", icon: "🎬", category: "portrait",
        description: "Classic Hollywood film noir style portrait with dramatic shadows",
        credit: "https://x.com/classiccinema",
        data: {
            subject_type: "portrait",
            style: "cinematic",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "caucasian",
                age_group: "adult",
                body_type: "slim",
                hair_style: "finger waves",
                hair_color: "platinum blonde",
                expression: "mysterious",
                pose: "glamour pose",
                clothing_style: "vintage glamour",
                clothing_type: "evening gown",
                clothing_color: "black satin",
                makeup_style: "classic hollywood",
                skin_type: "porcelain"
            }],
            eye_look: "seductive",
            eye_energy: "mysterious",
            eye_direction: "side glance",
            mouth_position: "red lips parted",
            mouth_energy: "sultry",
            face_features: "sculpted brows",
            hair_effect: "glossy shine",
            body_frame: "hourglass",
            body_definition: "elegant silhouette",
            skin_visible_areas: "face neck shoulders",
            skin_tone: "porcelain white",
            skin_texture: "flawless matte",
            skin_lighting_effect: "dramatic shadows",
            pose_position: "reclining",
            pose_base: "dramatic",
            pose_energy: "languid",
            clothing_effect: "satin sheen",
            clothing_details: "draped elegantly",
            device_type: "cigarette holder",
            device_details: "long black holder",
            prop_type: "pearl necklace",
            illusion_type: "none",
            illusion_device: "none",
            camera_style: "large format",
            shot_type: "studio portrait",
            photo_texture: "film grain classic",
            depth_of_field: "sharp focus",
            background_elements: "venetian blinds",
            background_atmosphere: "smoky mysterious",
            vibe_energy: "glamorous",
            vibe_aesthetic: "old Hollywood",
            vibe_authenticity: "period accurate",
            vibe_intimacy: "theatrical",
            lighting: "dramatic",
            mood: "mysterious",
            color_palette: "monochrome",
            setting: "film noir studio",
            season: "timeless",
            camera_angle: "three quarter view",
            quality_modifiers: "high contrast",
            _sceneObjects: [
                { label: "Venetian blinds", category: "props", location: "background", prominence: "secondary", color: "dark", state: "casting shadow stripes" },
                { label: "Smoke wisps", category: "atmosphere", location: "throughout", prominence: "secondary", state: "drifting lazily" },
                { label: "Crystal ashtray", category: "props", location: "foreground", prominence: "detail", color: "clear crystal" }
            ],
            _semanticRelationships: [
                { subject: "Light", action: "casting stripes through", object: "venetian blinds" },
                { subject: "Smoke", action: "curling around", object: "model" },
                { subject: "Model", action: "gazing", object: "into shadows" }
            ],
            additional_details: "Classic film noir portrait. Black and white aesthetic. Hard light through venetian blinds creating stripe shadows. Smoke atmosphere. 1940s Hollywood glamour. Dramatic chiaroscuro lighting. High contrast shadows."
        }
    },

    "ethereal_fairy_forest": {
        name: "Ethereal Fairy Forest", icon: "🧚", category: "fantasy",
        description: "Magical fairy-tale forest portrait with ethereal lighting and fantasy elements",
        credit: "https://x.com/fantasyart",
        data: {
            subject_type: "portrait",
            style: "fantasy",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "caucasian",
                age_group: "young adult",
                body_type: "petite",
                hair_style: "long flowing",
                hair_color: "strawberry blonde",
                expression: "gentle smile",
                pose: "graceful",
                clothing_style: "fantasy",
                clothing_type: "ethereal gown",
                clothing_color: "pale green",
                makeup_style: "natural minimal",
                skin_type: "fair"
            }],
            eye_look: "innocent",
            eye_energy: "magical",
            eye_direction: "looking up",
            mouth_position: "soft smile",
            mouth_energy: "gentle",
            face_features: "delicate elfin",
            hair_effect: "flowers woven in",
            body_frame: "delicate",
            body_definition: "slender",
            skin_visible_areas: "face arms",
            skin_tone: "pale luminous",
            skin_texture: "glowing porcelain",
            skin_lighting_effect: "dappled sunlight",
            pose_position: "sitting",
            pose_base: "graceful",
            pose_energy: "serene",
            clothing_effect: "flowing gossamer",
            clothing_details: "leaf embroidery",
            device_type: "magic wand",
            device_details: "glowing crystal tip",
            prop_type: "butterfly wings",
            illusion_type: "magical particles",
            illusion_device: "floating sparkles",
            camera_style: "DSLR photography",
            shot_type: "fantasy portrait",
            photo_texture: "soft dreamy",
            depth_of_field: "shallow ethereal",
            background_elements: "ancient trees",
            background_atmosphere: "magical misty",
            vibe_energy: "enchanting",
            vibe_aesthetic: "fairy tale",
            vibe_authenticity: "fantasy realism",
            vibe_intimacy: "magical encounter",
            lighting: "dappled sunlight",
            mood: "magical",
            color_palette: "pastel tones",
            setting: "enchanted forest",
            season: "spring",
            camera_angle: "slightly low",
            quality_modifiers: "ethereal quality",
            _sceneObjects: [
                { label: "Glowing fireflies", category: "creatures", location: "throughout", prominence: "secondary", color: "golden glow", state: "floating lazily" },
                { label: "Moss-covered tree", category: "natural", location: "background", prominence: "primary", color: "deep green", state: "ancient and magical" },
                { label: "Wildflowers", category: "natural", location: "ground", prominence: "secondary", color: "purple and white" },
                { label: "Translucent fairy wings", category: "fantasy", location: "back", prominence: "secondary", color: "iridescent", state: "catching light" }
            ],
            _semanticRelationships: [
                { subject: "Model", action: "sitting on", object: "moss-covered log" },
                { subject: "Fireflies", action: "dancing around", object: "model" },
                { subject: "Sunbeams", action: "filtering through", object: "forest canopy" }
            ],
            additional_details: "Ethereal fairy forest portrait. Dappled sunlight through ancient trees. Magical atmosphere with floating particles and fireflies. Translucent fairy wings catching light. Moss and wildflowers. Dreamy soft focus. Fantasy fairy tale aesthetic."
        }
    },

    "street_fashion_tokyo": {
        name: "Tokyo Street Fashion", icon: "🇯🇵", category: "street",
        description: "Harajuku-inspired street fashion portrait with bold colors and urban backdrop",
        credit: "https://x.com/tokyostreetstyle",
        data: {
            subject_type: "fashion",
            style: "photorealistic",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "east asian",
                age_group: "teenager",
                body_type: "petite",
                hair_style: "twin tails",
                hair_color: "pastel pink",
                expression: "playful",
                pose: "dynamic pose",
                clothing_style: "harajuku",
                clothing_type: "layered outfit",
                clothing_color: "multicolor pastels",
                makeup_style: "kawaii",
                skin_type: "fair"
            }],
            eye_look: "playful",
            eye_energy: "bright",
            eye_direction: "looking at viewer",
            mouth_position: "peace sign pose",
            mouth_energy: "cheerful",
            face_features: "round youthful",
            hair_effect: "colorful highlights",
            body_frame: "petite",
            body_definition: "youthful",
            skin_visible_areas: "face legs",
            skin_tone: "fair porcelain",
            skin_texture: "smooth flawless",
            skin_lighting_effect: "even soft light",
            pose_position: "standing",
            pose_base: "playful",
            pose_energy: "energetic",
            clothing_effect: "mixed textures",
            clothing_details: "kawaii accessories",
            device_type: "polaroid camera",
            device_details: "pastel pink camera",
            prop_type: "plushie bag",
            illusion_type: "none",
            illusion_device: "none",
            camera_style: "mirrorless",
            shot_type: "street photography",
            photo_texture: "crisp clean",
            depth_of_field: "medium depth",
            background_elements: "colorful storefronts",
            background_atmosphere: "vibrant urban",
            vibe_energy: "kawaii",
            vibe_aesthetic: "harajuku style",
            vibe_authenticity: "authentic street",
            vibe_intimacy: "candid moment",
            lighting: "overcast soft",
            mood: "playful",
            color_palette: "pastel rainbow",
            setting: "harajuku district",
            season: "spring",
            camera_angle: "eye level",
            quality_modifiers: "sharp detail",
            _sceneObjects: [
                { label: "Takeshita Street sign", category: "props", location: "background", prominence: "secondary", color: "red and white" },
                { label: "Colorful storefronts", category: "background", location: "background", prominence: "secondary", color: "pastel colors" },
                { label: "Plushie keychain bag", category: "props", location: "hand", prominence: "secondary", color: "pink" }
            ],
            _semanticRelationships: [
                { subject: "Model", action: "posing on", object: "Harajuku street" },
                { subject: "Outfit", action: "representing", object: "Harajuku fashion culture" },
                { subject: "Model", action: "making", object: "peace sign" }
            ],
            additional_details: "Harajuku street fashion portrait. Takeshita Street backdrop. Bold pastel colors and kawaii aesthetic. Layered colorful outfit with accessories. Twin tails with pastel pink hair. Authentic Tokyo street style. Energetic youthful vibe."
        }
    },

    "moody_rain_portrait": {
        name: "Moody Rain Portrait", icon: "🌧️", category: "portrait",
        description: "Atmospheric rainy day portrait with melancholic mood and cinematic feel",
        credit: "https://x.com/moodyphotography",
        data: {
            subject_type: "portrait",
            style: "cinematic",
            person_count: 1,
            persons: [{
                gender: "male",
                ethnicity: "caucasian",
                age_group: "adult",
                body_type: "average",
                hair_style: "messy wet",
                hair_color: "dark brown",
                expression: "contemplative",
                pose: "candid",
                clothing_style: "casual urban",
                clothing_type: "trench coat",
                clothing_color: "dark grey",
                makeup_style: "none",
                skin_type: "normal"
            }],
            eye_look: "distant",
            eye_energy: "thoughtful",
            eye_direction: "looking away",
            mouth_position: "neutral",
            mouth_energy: "pensive",
            face_features: "strong jawline",
            hair_effect: "wet from rain",
            body_frame: "medium",
            body_definition: "broad shoulders",
            skin_visible_areas: "face hands",
            skin_tone: "neutral cool",
            skin_texture: "natural with stubble",
            skin_lighting_effect: "diffused grey light",
            pose_position: "standing",
            pose_base: "contemplative",
            pose_energy: "still",
            clothing_effect: "rain-soaked",
            clothing_details: "collar turned up",
            device_type: "umbrella",
            device_details: "black umbrella closed",
            prop_type: "cigarette",
            illusion_type: "none",
            illusion_device: "none",
            camera_style: "mirrorless",
            shot_type: "environmental portrait",
            photo_texture: "moody grain",
            depth_of_field: "shallow focus",
            background_elements: "city street",
            background_atmosphere: "rainy urban",
            vibe_energy: "melancholic",
            vibe_aesthetic: "urban noir",
            vibe_authenticity: "raw emotional",
            vibe_intimacy: "introspective",
            lighting: "overcast",
            mood: "melancholic",
            color_palette: "desaturated",
            setting: "city street rain",
            season: "autumn",
            camera_angle: "eye level",
            quality_modifiers: "cinematic grade",
            _sceneObjects: [
                { label: "Rain droplets", category: "atmosphere", location: "throughout", prominence: "secondary", state: "falling continuously" },
                { label: "Wet pavement", category: "ground", location: "ground", prominence: "background", color: "dark reflective", state: "reflecting lights" },
                { label: "Street lamp", category: "props", location: "background", prominence: "secondary", color: "warm glow", state: "diffused in rain" },
                { label: "Parked cars", category: "background", location: "background", prominence: "background", state: "rain-covered" }
            ],
            _semanticRelationships: [
                { subject: "Model", action: "standing in", object: "rain" },
                { subject: "Rain", action: "falling on", object: "trench coat" },
                { subject: "Street lights", action: "reflecting in", object: "wet pavement" }
            ],
            additional_details: "Moody rain portrait. Heavy rain falling. Desaturated color grading. Urban city backdrop with diffused street lights. Wet hair and rain-soaked clothing. Contemplative expression. Cinematic atmosphere. Shallow depth of field with rain bokeh."
        }
    },

    "luxury_product_shot": {
        name: "Luxury Product Shot", icon: "💎", category: "product",
        description: "High-end luxury product photography with elegant lighting and premium feel",
        credit: "https://x.com/luxuryproduct",
        data: {
            subject_type: "product",
            style: "commercial",
            person_count: 0,
            product_type: "perfume bottle",
            product_material: "crystal glass",
            product_background: "gradient dark",
            eye_look: "none",
            eye_energy: "none",
            eye_direction: "none",
            mouth_position: "none",
            mouth_energy: "none",
            face_features: "none",
            hair_effect: "none",
            body_frame: "none",
            body_definition: "none",
            skin_visible_areas: "none",
            skin_tone: "none",
            skin_texture: "none",
            skin_lighting_effect: "none",
            pose_position: "none",
            pose_base: "none",
            pose_energy: "none",
            clothing_effect: "none",
            clothing_details: "none",
            device_type: "none",
            device_details: "none",
            prop_type: "gold accents",
            illusion_type: "reflection",
            illusion_device: "mirror surface",
            camera_style: "medium format",
            shot_type: "product photography",
            photo_texture: "ultra sharp",
            depth_of_field: "focus stacked",
            background_elements: "none minimal",
            background_atmosphere: "luxurious",
            vibe_energy: "premium",
            vibe_aesthetic: "luxury brand",
            vibe_authenticity: "commercial quality",
            vibe_intimacy: "aspirational",
            lighting: "studio lighting",
            mood: "elegant",
            color_palette: "black and gold",
            setting: "studio dark",
            season: "timeless",
            camera_angle: "product angle",
            quality_modifiers: "advertising quality",
            _sceneObjects: [
                { label: "Crystal perfume bottle", category: "product", location: "center", prominence: "primary", color: "clear with gold cap", material: "cut crystal", state: "pristine" },
                { label: "Black mirror surface", category: "surface", location: "ground", prominence: "secondary", color: "pure black", state: "perfect reflection" },
                { label: "Gold dust particles", category: "atmosphere", location: "background", prominence: "detail", color: "gold", state: "floating" }
            ],
            _semanticRelationships: [
                { subject: "Product", action: "reflecting on", object: "mirror surface" },
                { subject: "Light", action: "refracting through", object: "crystal glass" },
                { subject: "Gold particles", action: "floating around", object: "product" }
            ],
            additional_details: "Luxury product photography. Crystal perfume bottle with gold accents. Black mirror surface with perfect reflection. Studio lighting with dramatic highlights. Focus stacked for complete sharpness. Floating gold dust particles. Premium advertising quality."
        }
    },

    "vintage_polaroid_memory": {
        name: "Vintage Polaroid Memory", icon: "📸", category: "trending",
        description: "Nostalgic polaroid-style photo with vintage color grading and authentic film look",
        credit: "https://x.com/vintagephotos",
        data: {
            subject_type: "portrait",
            style: "vintage",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "caucasian",
                age_group: "young adult",
                body_type: "average",
                hair_style: "messy natural",
                hair_color: "natural brown",
                expression: "candid laugh",
                pose: "candid",
                clothing_style: "retro casual",
                clothing_type: "vintage tee",
                clothing_color: "faded colors",
                makeup_style: "no makeup",
                skin_type: "natural"
            }],
            eye_look: "joyful",
            eye_energy: "bright",
            eye_direction: "candid natural",
            mouth_position: "laughing",
            mouth_energy: "genuine joy",
            face_features: "natural freckles",
            hair_effect: "natural windswept",
            body_frame: "natural",
            body_definition: "relaxed",
            skin_visible_areas: "face arms",
            skin_tone: "natural warm",
            skin_texture: "natural imperfections",
            skin_lighting_effect: "warm vintage",
            pose_position: "sitting casual",
            pose_base: "relaxed candid",
            pose_energy: "carefree",
            clothing_effect: "vintage worn",
            clothing_details: "retro graphics",
            device_type: "none",
            device_details: "none",
            prop_type: "vintage sunglasses",
            illusion_type: "polaroid frame",
            illusion_device: "instant film border",
            camera_style: "polaroid instant",
            shot_type: "snapshot",
            photo_texture: "instant film grain",
            depth_of_field: "polaroid soft",
            background_elements: "summer scenery",
            background_atmosphere: "nostalgic",
            vibe_energy: "carefree",
            vibe_aesthetic: "analog nostalgia",
            vibe_authenticity: "genuine moment",
            vibe_intimacy: "personal memory",
            lighting: "natural light",
            mood: "nostalgic",
            color_palette: "vintage faded",
            setting: "backyard summer",
            season: "summer",
            camera_angle: "casual snapshot",
            quality_modifiers: "authentic polaroid",
            _sceneObjects: [
                { label: "Polaroid white border", category: "frame", location: "edges", prominence: "primary", color: "off-white", state: "slightly aged" },
                { label: "Summer grass", category: "natural", location: "background", prominence: "secondary", color: "warm green" },
                { label: "Vintage sunglasses", category: "props", location: "face/hand", prominence: "secondary", color: "tortoise shell" }
            ],
            _semanticRelationships: [
                { subject: "Photo", action: "captured in", object: "polaroid format" },
                { subject: "Model", action: "laughing at", object: "off-camera moment" },
                { subject: "Light", action: "creating", object: "vintage color cast" }
            ],
            additional_details: "Authentic polaroid instant film aesthetic. White polaroid border frame. Vintage color grading with faded tones. Candid laughing moment. Summer backyard setting. Genuine film grain and soft focus. 1980s nostalgic feel. Personal memory snapshot quality."
        }
    },

    "dramatic_sports_action": {
        name: "Dramatic Sports Action", icon: "⚡", category: "portrait",
        description: "High-energy sports action shot with dramatic lighting and motion blur",
        credit: "https://x.com/sportsphoto",
        data: {
            subject_type: "portrait",
            style: "photorealistic",
            person_count: 1,
            persons: [{
                gender: "male",
                ethnicity: "african",
                age_group: "young adult",
                body_type: "athletic",
                hair_style: "short fade",
                hair_color: "black",
                expression: "determined",
                pose: "action pose",
                clothing_style: "athletic",
                clothing_type: "basketball jersey",
                clothing_color: "team colors red",
                makeup_style: "none",
                skin_type: "dark"
            }],
            eye_look: "focused",
            eye_energy: "intense",
            eye_direction: "on target",
            mouth_position: "determined grimace",
            mouth_energy: "powerful",
            face_features: "strong defined",
            hair_effect: "sweat glistening",
            body_frame: "muscular athletic",
            body_definition: "defined muscles",
            skin_visible_areas: "arms face",
            skin_tone: "deep dark",
            skin_texture: "sweat sheen",
            skin_lighting_effect: "dramatic rim light",
            pose_position: "mid-jump",
            pose_base: "explosive",
            pose_energy: "maximum intensity",
            clothing_effect: "motion fabric",
            clothing_details: "jersey number visible",
            device_type: "basketball",
            device_details: "spalding official",
            prop_type: "sweat droplets",
            illusion_type: "motion blur",
            illusion_device: "speed lines",
            camera_style: "sports DSLR",
            shot_type: "sports photography",
            photo_texture: "crisp frozen action",
            depth_of_field: "isolated subject",
            background_elements: "arena crowd blur",
            background_atmosphere: "electric arena",
            vibe_energy: "explosive",
            vibe_aesthetic: "sports drama",
            vibe_authenticity: "live action",
            vibe_intimacy: "peak moment",
            lighting: "arena lighting",
            mood: "intense",
            color_palette: "high contrast",
            setting: "basketball arena",
            season: "indoor",
            camera_angle: "low angle",
            quality_modifiers: "freeze frame",
            _sceneObjects: [
                { label: "Basketball", category: "props", location: "hands", prominence: "primary", color: "orange", material: "leather", state: "in motion" },
                { label: "Sweat droplets", category: "detail", location: "face arms", prominence: "detail", state: "flying off body" },
                { label: "Arena lights", category: "lighting", location: "above", prominence: "secondary", state: "creating rim light" },
                { label: "Blurred crowd", category: "background", location: "background", prominence: "background", state: "motion blur" }
            ],
            _semanticRelationships: [
                { subject: "Athlete", action: "dunking", object: "basketball" },
                { subject: "Sweat", action: "flying off", object: "athlete's body" },
                { subject: "Arena lights", action: "backlighting", object: "athlete" }
            ],
            additional_details: "Dramatic sports action shot. Basketball player mid-dunk. Frozen motion with sweat droplets flying. Dramatic rim lighting from arena lights. Low angle power perspective. Blurred crowd background. Peak athletic moment. Intense facial expression. High shutter speed freeze frame."
        }
    },

    "cozy_cafe_lifestyle": {
        name: "Cozy Cafe Lifestyle", icon: "☕", category: "lifestyle",
        description: "Warm and inviting cafe lifestyle shot with natural window light",
        credit: "https://x.com/lifestylephotos",
        data: {
            subject_type: "lifestyle",
            style: "photorealistic",
            person_count: 1,
            persons: [{
                gender: "female",
                ethnicity: "mixed",
                age_group: "young adult",
                body_type: "average",
                hair_style: "loose waves",
                hair_color: "chestnut brown",
                expression: "content",
                pose: "relaxed sitting",
                clothing_style: "cozy casual",
                clothing_type: "oversized sweater",
                clothing_color: "cream knit",
                makeup_style: "natural minimal",
                skin_type: "normal"
            }],
            eye_look: "warm",
            eye_energy: "relaxed",
            eye_direction: "looking at book",
            mouth_position: "soft smile",
            mouth_energy: "content",
            face_features: "natural beauty",
            hair_effect: "soft natural",
            body_frame: "relaxed",
            body_definition: "cozy posture",
            skin_visible_areas: "face hands",
            skin_tone: "warm neutral",
            skin_texture: "natural healthy",
            skin_lighting_effect: "warm window light",
            pose_position: "sitting window seat",
            pose_base: "comfortable",
            pose_energy: "peaceful",
            clothing_effect: "chunky knit texture",
            clothing_details: "cable knit pattern",
            device_type: "book",
            device_details: "hardcover novel",
            prop_type: "coffee cup",
            illusion_type: "none",
            illusion_device: "none",
            camera_style: "mirrorless",
            shot_type: "lifestyle photography",
            photo_texture: "warm and soft",
            depth_of_field: "shallow cozy",
            background_elements: "cafe interior",
            background_atmosphere: "warm inviting",
            vibe_energy: "peaceful",
            vibe_aesthetic: "hygge cozy",
            vibe_authenticity: "genuine moment",
            vibe_intimacy: "personal comfort",
            lighting: "window light",
            mood: "cozy",
            color_palette: "warm earth tones",
            setting: "cozy cafe",
            season: "winter",
            camera_angle: "natural candid",
            quality_modifiers: "warm tones",
            _sceneObjects: [
                { label: "Ceramic coffee cup", category: "props", location: "hands/table", prominence: "secondary", color: "warm cream", state: "steaming" },
                { label: "Hardcover book", category: "props", location: "hands", prominence: "secondary", state: "open being read" },
                { label: "Rainy window", category: "background", location: "side", prominence: "secondary", state: "rain droplets on glass" },
                { label: "Wooden cafe table", category: "furniture", location: "foreground", prominence: "secondary", color: "warm wood", material: "rustic wood" }
            ],
            _semanticRelationships: [
                { subject: "Model", action: "reading", object: "book" },
                { subject: "Steam", action: "rising from", object: "coffee cup" },
                { subject: "Window light", action: "illuminating", object: "model's face" }
            ],
            additional_details: "Cozy cafe lifestyle portrait. Warm window light on rainy day. Oversized cream knit sweater. Steaming coffee cup on wooden table. Reading a book by the window. Rain droplets on glass. Hygge atmosphere. Warm earth tone color grading. Peaceful content expression."
        }
    }
};

// Export for use in main application
if (typeof module !== 'undefined' && module.exports) {
    module.exports = DEFAULT_PRESETS;
}
